# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
# Created with podman-5.3.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-04T16:52:17Z"
  labels:
    app: openfga-pod
  name: openfga-pod
spec:
  hostNetwork: true
  initContainers:
  - name: openfga-migrate
    image: docker.io/openfga/openfga:latest
    args:
    - migrate
    - --datastore-engine
    - postgres
    - --datastore-uri
    - postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_HOST
      value: localhost
    - name: POSTGRES_DB
      value: postgres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-pvc
  containers:
  - args:
    - run
    - --datastore-engine
    - postgres
    - --datastore-uri
    - postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable
    image: docker.io/openfga/openfga:latest
    name: openfga
    # ports:
    # - containerPort: 3000
    #   hostPort: 3000
    # - containerPort: 8080
    #   hostPort: 8080
    # - containerPort: 8081
    #   hostPort: 8081
    # securityContext:
    #   runAsNonRoot: true

  volumes:
  - name: postgres-pvc
    persistentVolumeClaim:
      claimName: postgres-pvc

