# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-04T16:49:53Z"
  labels:
    app: postgres
  name: postgres
spec:
  hostNetwork: true
  containers:
  - args:
    - postgres
    # ports:
    # - containerPort: 5432
    #   hostPort: 5432
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: password
    image: docker.io/library/postgres:14
    name: postgres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 4d9e2c29c2a92abe6404740a18fe3c81f4f3bdabe05d69a634dc882b474c3dc1-pvc
  volumes:
  - name: 4d9e2c29c2a92abe6404740a18fe3c81f4f3bdabe05d69a634dc882b474c3dc1-pvc
    persistentVolumeClaim:
      claimName: 4d9e2c29c2a92abe6404740a18fe3c81f4f3bdabe05d69a634dc882b474c3dc1

